# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
config:
  timeout: 2500
  tenant.name: "Digit BPA Productization"
  jenkins:
    url: http://168.63.253.5/
    username: TLhQsiSWbTyZ63bHOsYw3g==
    authtoken: tD02OTTFGNZvqmnAyPJvXA==
  digisign:
    enabled: false
  redis:
    flush.enabled: TRUE
    hostaddr: "172.16.1.4"
  cdn:
    enabled: FALSE
    s3.bucket: "NA"
    s3.accesskey: "NA"
    s3.secretkey: "NA"
  wildfly:
    home.path: 
    host.addr: 
      - "172.16.2.4"
    host.username: M3s06kFidYU5p4hdJe7AGg==
    host.password: M3s06kFidYU5p4hdJe7AGg==
    host.ssh.port: 22
    mgmt:
      port: 9990
      username: M3s06kFidYU5p4hdJe7AGg==
      password: M3s06kFidYU5p4hdJe7AGg==
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# Nexus Settings
# Retrive Digital Signature JAR and its dependency
nexus:
  url:  
  username: "NA"
  password: "NA"
  private.repository: NA
  group.id: NA
  artifact.id: NA
  package.type: NA
  version.id: NA
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# SMTP Settings
smtp:
  hostname: smtp.gmail.com
  port: 465
  username: 
  password: 
  receivers: 
